//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Xtrim_ERP.RichTextEditor;

namespace Xtrim_ERP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QatBelowRibbon {
            get {
                return ((bool)(this["QatBelowRibbon"]));
            }
            set {
                this["QatBelowRibbon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentDocuments {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentDocuments"]));
            }
            set {
                this["RecentDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowErrors {
            get {
                return ((bool)(this["ShowErrors"]));
            }
            set {
                this["ShowErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Dictionary {
            get {
                return ((string)(this["Dictionary"]));
            }
            set {
                this["Dictionary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShowErrors1 {
            get {
                return ((string)(this["ShowErrors1"]));
            }
            set {
                this["ShowErrors1"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsSerializeAs(global::System.Configuration.SettingsSerializeAs.Binary)]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public System.Collections.Generic.List<RecentDocumentItem> OpenedFiles
        {
            get
            {
                return this["OpenedFiles"] as System.Collections.Generic.List<RecentDocumentItem>;
            }
            set
            {
                this["OpenedFiles"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsSerializeAs(global::System.Configuration.SettingsSerializeAs.Binary)]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public System.Collections.Generic.List<RecentDocumentItem> SavedFiles
        {
            get
            {
                return this["SavedFiles"] as System.Collections.Generic.List<RecentDocumentItem>;
            }
            set
            {
                this["SavedFiles"] = value;
            }
        }
    }
}
